services:
  - type: web
    name: dmx-chatbot-web
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: FPT_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: EMBEDDING_API_URL
        sync: false
      - key: EMBEDDING_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
